#!/bin/bash
#
# remove_moved_files [-n] [-rename <suffix>]
# 
# where -n       : print what will be done, but don't do it
#       --rename : instead of deleting, add <suffix> to the end of the 
#                  file name
#
# Removes files moved by populate-lbnecode and populate-uboonecode
# from their original locations. Uses the <repo>-moved-files-<expt>code.txt
# files created by that script to find the files to delete.
#
# Must be run from the directory with the moved txt files created by
# the populate-* scripts. The target repositories are assumed to be
# in the same directory.

while (( $# )) ; do
  arg=$1
  case $arg in
    -n) do_nothing="true" ;;
    --rename) shift
              rename_suffix=$1
	      ;;
    *) echo "ERROR:  unrecognized argument \"$arg\""
       echo "Usage:  remove_moved_files [-n] [--rename <suffix>]"
       echo "        where -n       :  print what will be done without doing it"
       echo "              --rename : instead of deleting, add .<suffix> to"
       echo "                         the end of the file name"
       exit 1
       ;;
  esac
  shift
done

if [[ -n $rename_suffix ]] ; then
  command="mv"
else
  command="rm"
fi

[[ -n $do_nothing ]] && command="echo ${command}"


function remove_files () {
  repository=$1
  list_file=../$2
  
  cd $repository
  for file in `cat $list_file` ; do
    if [[ -e $file ]] ; then
      if [[ -n $rename_suffix ]] ; then
        echo "Renaming $file in $repository to ${file}.${rename_suffix}"
	second_arg="${file}.${rename_suffix}"
      else
        echo "Removing $file from $repository"
	second_arg=""
      fi
      $command $file $second_arg
    else
      echo "File $file not found in $repository"
    fi
  done
  cd ..
}

list_files="\
	larcore-moved-files-lbnecode.txt \
	larcore-moved-files-uboonecode.txt \
	lardata-moved-files-lbnecode.txt \
	lardata-moved-files-uboonecode.txt \
	lardata-uboone_datatypes-moved-files-uboonecode.txt \
	larevt-moved-files-lbnecode.txt \
	larevt-moved-files-uboonecode.txt \
	larsim-moved-files-lbnecode.txt \
	larsim-moved-files-uboonecode.txt"

for list in $list_files ; do
  repo=`echo $list | sed -e "s/-.*//"`
  remove_files $repo $list
done

